version: "3.8"

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    networks:
      - bot_network

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongo_data:
